# Generated by Django 4.0.4 on 2022-05-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0002_hall_session_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='Nuber of sit places',
            new_name='sitPlaces',
        ),
    ]
