# Generated by Django 4.0.4 on 2022-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0003_rename_nuber of sit places_hall_sitplaces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Place is avaliable',
            new_name='isAvaliable',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='Place Number',
            new_name='placeNumber',
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
