# Generated by Django 4.0.4 on 2022-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0004_rename_place is avaliable_place_isavaliable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
