# Generated by Django 4.0.4 on 2022-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0005_alter_session_session_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeHolder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
