# Generated by Django 4.0.4 on 2022-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0006_place_placeholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='sitPlaces',
            new_name='sitColumns',
        ),
        migrations.AddField(
            model_name='hall',
            name='sitRows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
