# Generated by Django 4.0.4 on 2022-05-09 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0007_rename_sitplaces_hall_sitcolumns_hall_sitrows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='sitColumns',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='sitRows',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
