# Generated by Django 4.0.4 on 2022-05-09 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0008_alter_hall_sitcolumns_alter_hall_sitrows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='sitColumns',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
    ]
