# Generated by Django 4.0.4 on 2022-05-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0009_alter_hall_sitcolumns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='cinema',
        ),
        migrations.AddField(
            model_name='cinema',
            name='halls',
            field=models.ManyToManyField(to='cinemaApp.hall'),
        ),
    ]
