# Generated by Django 4.0.4 on 2022-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0011_alter_cinema_id_alter_cinema_name_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
